### ISSUE TITLE
Console error after selecting calendar

### ISSUE THREAD

**Issue by mauthi** [enso-ui/calendar#1]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
After I select a calendar I get the following message in console:
![image](https://user-images.githubusercontent.com/7204559/66164541-33e6e000-e633-11e9-9307-b5068b34657a.png)

**Comment by aocneanu** [comment]
Will take care of it soon.

**Comment by aocneanu** [comment]
not applicable anymore
