### ISSUE TITLE
Translating the name of the calendar

### ISSUE THREAD

**Issue by heyner29** [enso-ui/calendar#15]
This is  a **feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
What do you think about the possibility of translating the name of the calendar, before opening a pull request I wanted to ask the question.

https://github.com/enso-ui/calendar/blob/3c7d21f2fb96a1e585b0731d167f99c5d4c8d517/src/bulma/pages/calendar/components/CalendarFilter.vue#L59

I say this because in my case I use the Spanish language and the birthday calendar is shown in English, in my project I made a patch to translate `{{ i18n(calendar.name) }}` it but it doesn't hurt to ask the question :)

**Comment by aocneanu** [comment]
I see no issue translating the calendar
